# Generated by Django 5.0 on 2023-12-25 12:07

import campus.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campus.thread'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=campus.models.Thread, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campus.post'),
        ),
    ]
