# Generated by Django 5.0 on 2023-12-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_post_vote_post_voters_thread_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(default='thread.jpg', upload_to='thread_pics'),
        ),
    ]
