# Generated by Django 5.0 on 2023-12-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0016_remove_post_vote_vote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
