# Generated by Django 5.0 on 2023-12-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0017_thread_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=100),
        ),
    ]
