# Generated by Django 5.0 on 2023-12-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0018_alter_thread_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='name',
            new_name='thread_name',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='title',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
