# Generated by Django 5.0 on 2023-12-31 18:41

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0020_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
