# Generated by Django 5.0 on 2024-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0024_alter_comment_content_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
