# Generated by Django 5.0 on 2024-01-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0026_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
