# Generated by Django 5.0.1 on 2024-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
