# Generated by Django 5.2 on 2025-08-12 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('org_type', models.CharField(choices=[('club', 'Club'), ('society', 'Society'), ('association', 'Association'), ('committee', 'Committee'), ('department', 'Department')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='org_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name', '-created_at'],
                'indexes': [models.Index(fields=['org_type', 'is_active'], name='organizatio_org_typ_257757_idx'), models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='pending', max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_memberships',
                'indexes': [models.Index(fields=['organization', 'status', 'role'], name='organizatio_organiz_edbb17_idx'), models.Index(fields=['user', 'status', 'role'], name='organizatio_user_id_697369_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
