# Generated by Django 5.2 on 2025-08-12 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thread_type', models.CharField(choices=[('general', 'General Discussion'), ('announcement', 'Announcement'), ('event', 'Event'), ('academic', 'Academic'), ('project', 'Project'), ('job', 'Job/Internship'), ('help', 'Help & Support')], default='general', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='campus.organization')),
            ],
            options={
                'db_table': 'threads',
                'ordering': ['-is_pinned', '-updated_at'],
                'indexes': [models.Index(fields=['organization', '-updated_at'], name='threads_organiz_f916d5_idx'), models.Index(fields=['thread_type'], name='threads_thread__d6f531_idx'), models.Index(fields=['-is_pinned', '-updated_at'], name='threads_is_pinn_9ed723_idx')],
            },
        ),
    ]
