# Generated by Django 5.2 on 2025-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_threadmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
