# Generated by Django 5.2 on 2025-08-31 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('threads', '0003_alter_threadmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('thread', 'Thread Members Only'), ('organization', 'Organization Members'), ('public', 'Public')], default='thread', help_text='Who can see this post?', max_length=20),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility'], name='posts_visibil_081a5d_idx'),
        ),
    ]
